### ISSUE TITLE
"Display WSL distro information as JSON form into stdout has stopped working"

### ISSUE THREAD

**Issue by xpufx** [rkttu/WslQuery#3]
I just installed the latest version of WSLManager and this is the pop up I get when I try to run it. Windows 10 with latest updates.

**Comment by mgurevin** [comment]
It doesn't work anymore because of the COM interface has been changed. I've got a patch to fix that: https://github.com/Biswa96/WslReverse/issues/1

**Comment by rkttu** [comment]
@mgurevin Thanks to the suggestion. Yes, you are correct.

Currently, I'm not maintaining this repository due to the incompatibility issues between each Windows 10 release, as you may already know.

I will update the readme to prevent any further misunderstanding. Sorry for the late response. 🙏
